[project]
name = "public-python-samples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.1",
]

[tool.pytest.ini_options]
pythonpath = [
  "samples/beginner-budget-cli/src",
  "samples/beginner-score-cli/src",
  "samples/csvfilter-cli/src",
  "samples/file-renamer-cli/src",
  "samples/logfilter-cli/src",
  "samples/password-generator-cli",
  "samples/python-common-sample/src",
  "samples/password-generator-gui/src",
]
testpaths = [
  "samples/beginner-budget-cli/tests",
  "samples/beginner-score-cli/tests",
  "samples/csvfilter-cli/tests",
  "samples/file-renamer-cli/tests",
  "samples/logfilter-cli/tests",
  "samples/python-common-sample/tests",
  "samples/password-generator-gui/tests",
]
